baseURL = "https://vikramrajsitpal.netlify.app"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Vikram's Den"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[params]
address = "California, USA"
author = "Vikramraj Sitpal"
copyright = "Copyright &copy; 2021 Vikramraj Sitpal"
description = "Vikramraj Sitpal's Personal Website"
email = ""
google_analytics_id = ""
home = "Home"
logo = "/images/gopher.png"
phone = ""
theme_color = "#116466"
[params.contact]
enable = true
form_action = "https://formspree.io/f/mjvjwbqd"
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "40.440624"
map_longitude = "-79.995888"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[[params.social]]
URL = "https://www.linkedin.com/in/vikramrajsitpal/"
icon = "ti-linkedin"
[[params.social]]
URL = "https://github.com/vikramrajsitpal"
icon = "ti-github"
[[params.social]]
URL = "https://www.instagram.com/vikramrajsitpal"
icon = "ti-instagram"
[[params.social]]
URL = "https://www.facebook.com/sitpalvikramraj"
icon = "ti-facebook"
[[params.social]]
URL = "https://www.twitter.com/chaklu"
icon = "ti-twitter-alt"
